"""Ensure the user-facing M1 proof is generated by the simulator."""

import json
import unittest
from pathlib import Path

from project_b.neurons import LIFParameters
from scripts.demo_m1 import build_report, draw_voltage_svg

ROOT = Path(__file__).resolve().parents[1]


class DemoTests(unittest.TestCase):
    def test_report_and_trace_are_reproducible(self) -> None:
        config_path = ROOT / "configs" / "m1_demos.yaml"
        report, trace = build_report(config_path)
        repeated, repeated_trace = build_report(config_path)
        self.assertEqual(json.dumps(report, sort_keys=True),
                         json.dumps(repeated, sort_keys=True))
        self.assertEqual(trace, repeated_trace)
        self.assertEqual(report["single_neuron"]["spike_times_us"],
                         [7_000, 17_000, 27_000])
        self.assertEqual(report["excitation_a_to_b"]["b_spikes_us"], [5_000])
        self.assertEqual(report["inhibition_a_to_b"]["b_with_inhibition_us"],
                         [22_000])
        self.assertEqual(report["chain_a_to_b_to_c"]["c_spikes_us"], [9_000])
        svg = draw_voltage_svg(trace, LIFParameters(refractory_us=3_000), 1_000)
        self.assertIn("threshold", svg)
        self.assertEqual(svg.count("SPIKE"), 3)


if __name__ == "__main__":
    unittest.main()
