"""Build a navigable index without relocating historical research reports."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
CATALOG = DOCS / "catalog.md"


def section(path: Path) -> str:
    name = path.name.upper()
    if path.parent != DOCS:
        return "New guides and history"
    if name in {"INDEX.MD", "PROJECT-STATUS.MD", "ARCHITECTURE.MD", "REPRODUCIBILITY.MD"}:
        return "New guides and history"
    if name.startswith("MALECNS_") and any(
        key in name
        for key in ("LEARNING", "DAN_BRIDGE", "LEVEL4", "MAX_PLASTICITY")
    ):
        return "MaleCNS internal and moving learning"
    if name.startswith("LARVAL_"):
        return "Larval work"
    if name.startswith(("A1_", "A2_", "A3_", "A4_", "A5_", "A8_", "A9_", "A10_", "A11_", "BRANCH_A_")):
        return "Infrastructure and evaluation"
    if name.startswith(("B1_", "B2_", "B3_", "B5_", "B6_", "BRANCH_B_")):
        return "Pathway and candidate decisions"
    if name.startswith(("CIRCUIT_", "ELECTRICAL_", "DN_", "MALECNS_")):
        return "MaleCNS data, anatomy, and electrical audits"
    return "Other reports and protocols"


def title(path: Path) -> str:
    for line in path.read_text(encoding="utf-8-sig", errors="replace").splitlines():
        if line.startswith("# "):
            return line[2:].strip().replace("[", "\\[").replace("]", "\\]")
    return path.stem.replace("_", " ")


def render() -> str:
    groups: dict[str, list[Path]] = {}
    for path in DOCS.rglob("*.md"):
        if path == CATALOG:
            continue
        groups.setdefault(section(path), []).append(path)

    preferred = [
        "New guides and history",
        "MaleCNS internal and moving learning",
        "MaleCNS data, anatomy, and electrical audits",
        "Larval work",
        "Infrastructure and evaluation",
        "Pathway and candidate decisions",
        "Other reports and protocols",
    ]
    lines = [
        "# Complete document catalog",
        "",
        "This index lists the Markdown reports preserved under `docs/`. The [documentation guide](index.md) is the shorter route through the project. Titles below come from the files; a report's original PASS or FAIL remains authoritative.",
        "",
    ]
    for group in preferred:
        paths = groups.get(group, [])
        if not paths:
            continue
        lines.extend([f"## {group}", ""])
        for path in sorted(paths, key=lambda item: item.relative_to(DOCS).as_posix().lower()):
            rel = path.relative_to(DOCS).as_posix()
            lines.append(f"- [{title(path)}]({rel})")
        lines.append("")
    lines.extend(
        [
            "Generated by `python scripts/build_docs_catalog.py`. To verify it is current, run `python scripts/build_docs_catalog.py --check`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the saved catalog is stale")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not CATALOG.exists() or CATALOG.read_text(encoding="utf-8") != expected:
            print("docs/catalog.md is missing or stale")
            return 1
        print("docs/catalog.md is current")
        return 0
    CATALOG.write_text(expected, encoding="utf-8")
    print(f"Wrote {CATALOG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
